name = "proxlock-landing"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-01-30"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true